// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1074023038;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__close_session_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "close_session",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::close_session(api_session_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__create_empty_model_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_empty_model",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::create_empty_model())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__create_project_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_project",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::create_project(api_name))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__element_details_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "element_details",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_element_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Ok::<_, ()>(crate::api::element_details(api_session_id, api_element_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__execute_command_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "execute_command",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_request = <crate::session::CommandRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Ok::<_, ()>(crate::api::execute_command(api_session_id, api_request))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_kernel_status_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_kernel_status",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::get_kernel_status())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__load_session_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_session",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::load_session(api_data))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__open_session_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_session",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            let api_project_type = <String>::sse_decode(&mut deserializer);
            let api_land_area_m2 = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::open_session(
                    api_name,
                    api_project_type,
                    api_land_area_m2,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__redo_command_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "redo_command",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::redo_command(api_session_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__render_data_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "render_data",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::render_data(api_session_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__save_session_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_session",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::save_session(api_session_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__session_state_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "session_state",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::session_state(api_session_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__set_active_level_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_active_level",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_level_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Ok::<_, ()>(crate::api::set_active_level(api_session_id, api_level_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__snap_point_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "snap_point",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            let api_x_m = <f64>::sse_decode(&mut deserializer);
            let api_y_m = <f64>::sse_decode(&mut deserializer);
            let api_z_m = <f64>::sse_decode(&mut deserializer);
            let api_tolerance_m = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::snap_point(
                    api_session_id,
                    api_x_m,
                    api_y_m,
                    api_z_m,
                    api_tolerance_m,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__undo_command_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "undo_command",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::undo_command(api_session_id))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::session::CommandRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_command = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_elementId = <String>::sse_decode(deserializer);
        let mut var_levelId = <String>::sse_decode(deserializer);
        let mut var_baseLevelId = <String>::sse_decode(deserializer);
        let mut var_topLevelId = <String>::sse_decode(deserializer);
        let mut var_xM = <f64>::sse_decode(deserializer);
        let mut var_yM = <f64>::sse_decode(deserializer);
        let mut var_widthM = <f64>::sse_decode(deserializer);
        let mut var_depthM = <f64>::sse_decode(deserializer);
        let mut var_thicknessM = <f64>::sse_decode(deserializer);
        let mut var_widthMm = <f64>::sse_decode(deserializer);
        let mut var_depthMm = <f64>::sse_decode(deserializer);
        let mut var_startXM = <f64>::sse_decode(deserializer);
        let mut var_startYM = <f64>::sse_decode(deserializer);
        let mut var_endXM = <f64>::sse_decode(deserializer);
        let mut var_endYM = <f64>::sse_decode(deserializer);
        let mut var_dxM = <f64>::sse_decode(deserializer);
        let mut var_dyM = <f64>::sse_decode(deserializer);
        let mut var_dzM = <f64>::sse_decode(deserializer);
        let mut var_direction = <String>::sse_decode(deserializer);
        let mut var_offsetM = <f64>::sse_decode(deserializer);
        let mut var_elevationM = <f64>::sse_decode(deserializer);
        let mut var_foundationKind = <String>::sse_decode(deserializer);
        let mut var_points = <Vec<f64>>::sse_decode(deserializer);
        return crate::session::CommandRequest {
            command: var_command,
            name: var_name,
            element_id: var_elementId,
            level_id: var_levelId,
            base_level_id: var_baseLevelId,
            top_level_id: var_topLevelId,
            x_m: var_xM,
            y_m: var_yM,
            width_m: var_widthM,
            depth_m: var_depthM,
            thickness_m: var_thicknessM,
            width_mm: var_widthMm,
            depth_mm: var_depthMm,
            start_x_m: var_startXM,
            start_y_m: var_startYM,
            end_x_m: var_endXM,
            end_y_m: var_endYM,
            dx_m: var_dxM,
            dy_m: var_dyM,
            dz_m: var_dzM,
            direction: var_direction,
            offset_m: var_offsetM,
            elevation_m: var_elevationM,
            foundation_kind: var_foundationKind,
            points: var_points,
        };
    }
}

impl SseDecode for crate::session::CommandResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_revision = <u64>::sse_decode(deserializer);
        let mut var_changedIds = <Vec<String>>::sse_decode(deserializer);
        let mut var_canUndo = <bool>::sse_decode(deserializer);
        let mut var_canRedo = <bool>::sse_decode(deserializer);
        return crate::session::CommandResult {
            ok: var_ok,
            message: var_message,
            label: var_label,
            revision: var_revision,
            changed_ids: var_changedIds,
            can_undo: var_canUndo,
            can_redo: var_canRedo,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::session::SnapCandidate> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::session::SnapCandidate>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::model::summary::ModelSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_schemaVersion = <u32>::sse_decode(deserializer);
        let mut var_projectId = <String>::sse_decode(deserializer);
        let mut var_revision = <u64>::sse_decode(deserializer);
        let mut var_levels = <u32>::sse_decode(deserializer);
        let mut var_grids = <u32>::sse_decode(deserializer);
        let mut var_materials = <u32>::sse_decode(deserializer);
        let mut var_crossSections = <u32>::sse_decode(deserializer);
        let mut var_elements = <u32>::sse_decode(deserializer);
        return crate::model::summary::ModelSummary {
            schema_version: var_schemaVersion,
            project_id: var_projectId,
            revision: var_revision,
            levels: var_levels,
            grids: var_grids,
            materials: var_materials,
            cross_sections: var_crossSections,
            elements: var_elements,
        };
    }
}

impl SseDecode for crate::api::OpenSessionResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_stateJson = <String>::sse_decode(deserializer);
        return crate::api::OpenSessionResult {
            ok: var_ok,
            message: var_message,
            session_id: var_sessionId,
            state_json: var_stateJson,
        };
    }
}

impl SseDecode for crate::project::ProjectSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_formatVersion = <u32>::sse_decode(deserializer);
        let mut var_modelSchemaVersion = <u32>::sse_decode(deserializer);
        let mut var_projectId = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_projectType = <String>::sse_decode(deserializer);
        let mut var_landAreaM2 = <f64>::sse_decode(deserializer);
        let mut var_revision = <u64>::sse_decode(deserializer);
        let mut var_levels = <u32>::sse_decode(deserializer);
        let mut var_grids = <u32>::sse_decode(deserializer);
        let mut var_materials = <u32>::sse_decode(deserializer);
        let mut var_crossSections = <u32>::sse_decode(deserializer);
        let mut var_elements = <u32>::sse_decode(deserializer);
        return crate::project::ProjectSummary {
            format_version: var_formatVersion,
            model_schema_version: var_modelSchemaVersion,
            project_id: var_projectId,
            name: var_name,
            project_type: var_projectType,
            land_area_m2: var_landAreaM2,
            revision: var_revision,
            levels: var_levels,
            grids: var_grids,
            materials: var_materials,
            cross_sections: var_crossSections,
            elements: var_elements,
        };
    }
}

impl SseDecode for crate::session::SnapCandidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_xM = <f64>::sse_decode(deserializer);
        let mut var_yM = <f64>::sse_decode(deserializer);
        let mut var_zM = <f64>::sse_decode(deserializer);
        let mut var_distanceM = <f64>::sse_decode(deserializer);
        return crate::session::SnapCandidate {
            kind: var_kind,
            label: var_label,
            x_m: var_xM,
            y_m: var_yM,
            z_m: var_zM,
            distance_m: var_distanceM,
        };
    }
}

impl SseDecode for crate::session::SnapResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_snapped = <bool>::sse_decode(deserializer);
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_xM = <f64>::sse_decode(deserializer);
        let mut var_yM = <f64>::sse_decode(deserializer);
        let mut var_zM = <f64>::sse_decode(deserializer);
        let mut var_candidates = <Vec<crate::session::SnapCandidate>>::sse_decode(deserializer);
        return crate::session::SnapResult {
            snapped: var_snapped,
            kind: var_kind,
            label: var_label,
            x_m: var_xM,
            y_m: var_yM,
            z_m: var_zM,
            candidates: var_candidates,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        7 => wire__crate__api__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__close_session_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__create_empty_model_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__create_project_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__element_details_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__execute_command_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__get_kernel_status_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__load_session_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__open_session_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__redo_command_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__render_data_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__save_session_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__session_state_impl(ptr, rust_vec_len, data_len),
        14 => wire__crate__api__set_active_level_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__snap_point_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__undo_command_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::session::CommandRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.command.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.element_id.into_into_dart().into_dart(),
            self.level_id.into_into_dart().into_dart(),
            self.base_level_id.into_into_dart().into_dart(),
            self.top_level_id.into_into_dart().into_dart(),
            self.x_m.into_into_dart().into_dart(),
            self.y_m.into_into_dart().into_dart(),
            self.width_m.into_into_dart().into_dart(),
            self.depth_m.into_into_dart().into_dart(),
            self.thickness_m.into_into_dart().into_dart(),
            self.width_mm.into_into_dart().into_dart(),
            self.depth_mm.into_into_dart().into_dart(),
            self.start_x_m.into_into_dart().into_dart(),
            self.start_y_m.into_into_dart().into_dart(),
            self.end_x_m.into_into_dart().into_dart(),
            self.end_y_m.into_into_dart().into_dart(),
            self.dx_m.into_into_dart().into_dart(),
            self.dy_m.into_into_dart().into_dart(),
            self.dz_m.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.offset_m.into_into_dart().into_dart(),
            self.elevation_m.into_into_dart().into_dart(),
            self.foundation_kind.into_into_dart().into_dart(),
            self.points.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::session::CommandRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::session::CommandRequest>
    for crate::session::CommandRequest
{
    fn into_into_dart(self) -> crate::session::CommandRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::session::CommandResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.revision.into_into_dart().into_dart(),
            self.changed_ids.into_into_dart().into_dart(),
            self.can_undo.into_into_dart().into_dart(),
            self.can_redo.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::session::CommandResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::session::CommandResult>
    for crate::session::CommandResult
{
    fn into_into_dart(self) -> crate::session::CommandResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::model::summary::ModelSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.schema_version.into_into_dart().into_dart(),
            self.project_id.into_into_dart().into_dart(),
            self.revision.into_into_dart().into_dart(),
            self.levels.into_into_dart().into_dart(),
            self.grids.into_into_dart().into_dart(),
            self.materials.into_into_dart().into_dart(),
            self.cross_sections.into_into_dart().into_dart(),
            self.elements.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::model::summary::ModelSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::model::summary::ModelSummary>
    for crate::model::summary::ModelSummary
{
    fn into_into_dart(self) -> crate::model::summary::ModelSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::OpenSessionResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.session_id.into_into_dart().into_dart(),
            self.state_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::OpenSessionResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::OpenSessionResult>
    for crate::api::OpenSessionResult
{
    fn into_into_dart(self) -> crate::api::OpenSessionResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::project::ProjectSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.format_version.into_into_dart().into_dart(),
            self.model_schema_version.into_into_dart().into_dart(),
            self.project_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.project_type.into_into_dart().into_dart(),
            self.land_area_m2.into_into_dart().into_dart(),
            self.revision.into_into_dart().into_dart(),
            self.levels.into_into_dart().into_dart(),
            self.grids.into_into_dart().into_dart(),
            self.materials.into_into_dart().into_dart(),
            self.cross_sections.into_into_dart().into_dart(),
            self.elements.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::project::ProjectSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::project::ProjectSummary>
    for crate::project::ProjectSummary
{
    fn into_into_dart(self) -> crate::project::ProjectSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::session::SnapCandidate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.x_m.into_into_dart().into_dart(),
            self.y_m.into_into_dart().into_dart(),
            self.z_m.into_into_dart().into_dart(),
            self.distance_m.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::session::SnapCandidate {}
impl flutter_rust_bridge::IntoIntoDart<crate::session::SnapCandidate>
    for crate::session::SnapCandidate
{
    fn into_into_dart(self) -> crate::session::SnapCandidate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::session::SnapResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.snapped.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.x_m.into_into_dart().into_dart(),
            self.y_m.into_into_dart().into_dart(),
            self.z_m.into_into_dart().into_dart(),
            self.candidates.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::session::SnapResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::session::SnapResult> for crate::session::SnapResult {
    fn into_into_dart(self) -> crate::session::SnapResult {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::session::CommandRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.command, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.element_id, serializer);
        <String>::sse_encode(self.level_id, serializer);
        <String>::sse_encode(self.base_level_id, serializer);
        <String>::sse_encode(self.top_level_id, serializer);
        <f64>::sse_encode(self.x_m, serializer);
        <f64>::sse_encode(self.y_m, serializer);
        <f64>::sse_encode(self.width_m, serializer);
        <f64>::sse_encode(self.depth_m, serializer);
        <f64>::sse_encode(self.thickness_m, serializer);
        <f64>::sse_encode(self.width_mm, serializer);
        <f64>::sse_encode(self.depth_mm, serializer);
        <f64>::sse_encode(self.start_x_m, serializer);
        <f64>::sse_encode(self.start_y_m, serializer);
        <f64>::sse_encode(self.end_x_m, serializer);
        <f64>::sse_encode(self.end_y_m, serializer);
        <f64>::sse_encode(self.dx_m, serializer);
        <f64>::sse_encode(self.dy_m, serializer);
        <f64>::sse_encode(self.dz_m, serializer);
        <String>::sse_encode(self.direction, serializer);
        <f64>::sse_encode(self.offset_m, serializer);
        <f64>::sse_encode(self.elevation_m, serializer);
        <String>::sse_encode(self.foundation_kind, serializer);
        <Vec<f64>>::sse_encode(self.points, serializer);
    }
}

impl SseEncode for crate::session::CommandResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <String>::sse_encode(self.message, serializer);
        <String>::sse_encode(self.label, serializer);
        <u64>::sse_encode(self.revision, serializer);
        <Vec<String>>::sse_encode(self.changed_ids, serializer);
        <bool>::sse_encode(self.can_undo, serializer);
        <bool>::sse_encode(self.can_redo, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::session::SnapCandidate> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::session::SnapCandidate>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::model::summary::ModelSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.schema_version, serializer);
        <String>::sse_encode(self.project_id, serializer);
        <u64>::sse_encode(self.revision, serializer);
        <u32>::sse_encode(self.levels, serializer);
        <u32>::sse_encode(self.grids, serializer);
        <u32>::sse_encode(self.materials, serializer);
        <u32>::sse_encode(self.cross_sections, serializer);
        <u32>::sse_encode(self.elements, serializer);
    }
}

impl SseEncode for crate::api::OpenSessionResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <String>::sse_encode(self.message, serializer);
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.state_json, serializer);
    }
}

impl SseEncode for crate::project::ProjectSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.format_version, serializer);
        <u32>::sse_encode(self.model_schema_version, serializer);
        <String>::sse_encode(self.project_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.project_type, serializer);
        <f64>::sse_encode(self.land_area_m2, serializer);
        <u64>::sse_encode(self.revision, serializer);
        <u32>::sse_encode(self.levels, serializer);
        <u32>::sse_encode(self.grids, serializer);
        <u32>::sse_encode(self.materials, serializer);
        <u32>::sse_encode(self.cross_sections, serializer);
        <u32>::sse_encode(self.elements, serializer);
    }
}

impl SseEncode for crate::session::SnapCandidate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.label, serializer);
        <f64>::sse_encode(self.x_m, serializer);
        <f64>::sse_encode(self.y_m, serializer);
        <f64>::sse_encode(self.z_m, serializer);
        <f64>::sse_encode(self.distance_m, serializer);
    }
}

impl SseEncode for crate::session::SnapResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.snapped, serializer);
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.label, serializer);
        <f64>::sse_encode(self.x_m, serializer);
        <f64>::sse_encode(self.y_m, serializer);
        <f64>::sse_encode(self.z_m, serializer);
        <Vec<crate::session::SnapCandidate>>::sse_encode(self.candidates, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
